export const PLACEMENT = [
  "A zone exports a value that only one other zone uses, so the seam it crosses carries nothing a second caller needs. A symbol in a shared package that one consumer uses is not shared, it is that consumer's code in the wrong place.",
  "",
  "The shape of the finding decides what moves, so do not work it out again from the file:",
  "- `declares N exports, all used only by ...` means nothing outside that one consumer reads the file at all, its own zone included. Move the file into that consumer and every finding on it closes at once.",
  "- `declares <name>, used only by ...` means the rest of the file has other readers, so the file stays and only that declaration is in question.",
  "- `declares <name>, used outside its zone only by ...` means the declaring zone reads it too. Moving it leaves that reader crossing a boundary, so check what the declaring zone may reach before you move anything, and prefer dissolving the value into its one outside consumer.",
  "- `... and by this file as well` means another declaration here reads it, so the file it leaves would have to import it back. Move that declaration with it, or leave both where they are. This clause can ride along with the one above, and then both are true.",
  "- `while <zone> reads it too but is <role>, so it does not count` means the reader that would have made this a shared value is silenced by its role. Moving the declaration anywhere but into the consumer named closes nothing, because that reader will not count wherever it sits. So either the role is wrong, and the logic that reader owns belongs in a zone that counts, or the value belongs to the consumer named. A wiring zone holding a loop of its own is the usual cause: give that loop a home outside the composition root and it becomes a second reader.",
  "",
  "Before moving a single declaration, ask whether the seam should carry it at all. A value the caller derives from an argument it hands the same collaborator belongs to that collaborator, which can derive it itself and leave the two nothing to disagree about. Moving it is the fix only when it does not.",
  "",
  "Not the fix:",
  "- Giving a zone a role so it stops counting as a consumer. A role is honest only for a zone that never owns what it uses.",
  "- Leaving it because a second consumer may arrive later. That is a reason to move it back then, not a reason to leave it now.",
  "",
  "Type-only edges are not reported, because a type can be used through a value without ever being imported.",
].join("\n");

export const INTERNALS = [
  "A test reaches a symbol that nothing outside its own directory calls, so the test knows a decomposition none of the callers know. Fold that symbol into the neighbour that uses it and the behaviour is unchanged while the test breaks, which is what it means for a test to be bound to an implementation detail rather than to behaviour.",
  "",
  "Do this:",
  "- Reach the behaviour through the surface the production callers already go through, and the split underneath is free to move.",
  "- When that is genuinely too expensive, because a handful of cases each need their own fixture to drive from outside, let the symbol become a module with a caller of its own.",
  "",
  "Not the fix:",
  "- Widening the surface so the direct test becomes legitimate.",
  "- Adding a production caller to justify it.",
  "",
  "Both leave the codebase worse than the finding did. A zone with the `wiring` role is not reported, because a composition root has no internals to protect, and something the package publishes belongs in a zone with the `api` role.",
].join("\n");

export const FOR_TESTS = [
  "Nothing outside the tests uses this export, so it is public only so a test can reach in.",
  "",
  "Do this:",
  "- Reach the behaviour through the surface production actually calls, and the export can go back to being private.",
  "- If the piece genuinely deserves its own test, let it become its own module with a real caller rather than a widened surface on this one.",
  "- A helper that exists purely to serve tests belongs in a zone with the `tests` role, not in the source it props up.",
  "",
  "Something a package publishes belongs in a zone with the `api` role, whose consumers this analysis cannot see.",
  "",
  "Not the fix: adding a production caller so the export has a real consumer. That is the one change that leaves the codebase worse than the finding did.",
].join("\n");
